import json, statistics
from collections import defaultdict, Counter
S="/private/tmp/claude-501/-Users-mamass/ef7d9418-a7df-428a-9dbf-2c7a29b2b0aa/scratchpad"
rows=[r for r in json.load(open(f"{S}/barometre-results.json")) if "score" in r and r.get("status")==200]
# regroupement lisible des catégories OSM
GROUP={"restaurant":"Restaurants & bars","fast_food":"Restaurants & bars","cafe":"Restaurants & bars","bar":"Restaurants & bars","pub":"Restaurants & bars","ice_cream":"Restaurants & bars","bakery":"Commerces alimentaires","deli":"Commerces alimentaires","butcher":"Commerces alimentaires","convenience":"Commerces alimentaires","wine":"Commerces alimentaires","greengrocer":"Commerces alimentaires","cheese":"Commerces alimentaires","chocolate":"Commerces alimentaires","pastry":"Commerces alimentaires","tea":"Commerces alimentaires","coffee":"Commerces alimentaires","estate_agent":"Immobilier","insurance":"Assurance & finance","financial_advisor":"Assurance & finance","accountant":"Services aux entreprises","lawyer":"Services aux entreprises","notary":"Services aux entreprises","company":"Services aux entreprises","it":"Services aux entreprises","consulting":"Services aux entreprises","employment_agency":"Services aux entreprises","advertising_agency":"Services aux entreprises","architect":"Services aux entreprises","coworking":"Services aux entreprises","hairdresser":"Beauté & bien-être","beauty":"Beauté & bien-être","massage":"Beauté & bien-être","tattoo":"Beauté & bien-être","cosmetics":"Beauté & bien-être","fitness_centre":"Beauté & bien-être","yoga":"Beauté & bien-être","pharmacy":"Santé","dentist":"Santé","doctors":"Santé","optician":"Santé","physiotherapist":"Santé","veterinary":"Santé","hotel":"Hôtels & hébergement","guest_house":"Hôtels & hébergement","hostel":"Hôtels & hébergement","apartment":"Hôtels & hébergement","clothes":"Commerces non alimentaires","shoes":"Commerces non alimentaires","books":"Commerces non alimentaires","jewelry":"Commerces non alimentaires","furniture":"Commerces non alimentaires","florist":"Commerces non alimentaires","gift":"Commerces non alimentaires","toys":"Commerces non alimentaires","sports":"Commerces non alimentaires","bicycle":"Commerces non alimentaires","electronics":"Commerces non alimentaires","music":"Commerces non alimentaires","art":"Commerces non alimentaires","interior_decoration":"Commerces non alimentaires","car_repair":"Auto & artisans","car":"Auto & artisans","electrician":"Auto & artisans","plumber":"Auto & artisans","carpenter":"Auto & artisans","painter":"Auto & artisans","hvac":"Auto & artisans","roofer":"Auto & artisans","driving_school":"Auto & artisans"}
by=defaultdict(list)
for r in rows: by[GROUP.get(r["cat"],"Autres")].append(r)
def pct_fail(rs,cid,statuses=("fail",)): 
    n=len(rs); return round(100*sum(1 for r in rs for c in r["checks"] if c["id"]==cid and c["status"] in statuses)/n)
print(f"{'Secteur':28s} {'n':>4s} {'score':>6s} {'meta absente':>13s} {'H1 KO':>6s} {'JSON-LD absent':>15s} {'OG absent':>10s}")
for g,rs in sorted(by.items(), key=lambda kv:-len(kv[1])):
    if len(rs)<10: continue
    print(f"{g:28s} {len(rs):4d} {round(statistics.mean(r['score'] for r in rs),1):6.1f} {pct_fail(rs,'meta-description'):12d}% {pct_fail(rs,'h1',('fail','warning')):5d}% {pct_fail(rs,'structured-data'):14d}% {pct_fail(rs,'og-tags'):9d}%")
print("\nTop 5 des sites les mieux notés (à citer positivement, avec leur accord ou non ?) :")
for r in sorted(rows,key=lambda r:-r["score"])[:5]: print("  ",r["score"],r["name"],r["host"],r["cat"])
